### ISSUE TITLE
Notes on getting hyo2_bag running on Windows 11/Python3.12/venv

### ISSUE THREAD

**Issue by heathhenley** [hydroffice/hyo2_bag#3]
First of all, thanks a lot for putting together this package - I needed something simple to manipulate BAGs and the differences in versions / details were causing me some pain trying to use the raw GDAL cli. 

I hit some snags getting it running on windows 11 in a python 3.12 venv, here's the notes on what I did to get it going. I'm just posting in case someone comes across it and has any issues setting up the environment. If you decide that any subset / cleaned up version of these could be included to improve the project, I would be happy to work on a patch. 

## Notes
There seems to be a dependency on `hyo2.abc.logging` that I couldn't find in the repo when running this. I swapped the calls to use the normal logger and removed the dependency and things seem to work (not suggesting that's necessarily the solution, just that it got my to point of being able to run. 

I took notes as a worked through getting it running on Windows 11 in a venv with python 3.12 - here's what I found:

- Install OSGeo4W tools (I had already done this but they're needed) 
- Update the PROJ_LIB env var to point at the installed proj folder (C:\OSGeo4W\share\proj ) to resolve "PROJ: proj_create_from_database: Cannot find proj.db"
- Install GDAL python manually from wheel (windows issue) ( https://github.com/cgohlke/geospatial-wheels/releases/tag/v2024.2.18)
- pip install pyproj python-dateutil  (and probably others, my virtual env dependencies pasted below)

To get all the examples running, as I said I removed the missing abc.logging module and used the default python logger instead. 

I found that running the tools scripts with a subprocess call was not using the same python environment as as my current env (the tools were runnable from my main shell, but failing with import errors in the subprocess call). As a workaround, I just switched to call their main functions and passed in the expected arguments. 

I also removed `__import__('pkg_resources').declare_namespace(__name__)` from the main __init__ file, probably breaks somethign with packaging but I couldn't get it running locally otherwise. 

Here's the hacky branch I have going that lets me run the bag_* and run_* examples (so far, haven't touched the using_* examples yet): https://github.com/hydroffice/hyo2_bag/compare/master...heathhenley:hyo2_bag:dev_hh_example_tweaks?expand=1

Here's my pip freeze output: 

```
certifi==2024.2.2
contourpy==1.2.0
cycler==0.12.1
fonttools==4.49.0
GDAL @ file:///C:/users/heath/Desktop/GDAL-3.8.4-cp312-cp312-win_amd64.whl#sha256=841c9569814fb5167e5b5652cf244f20a91051d1d6dd1ee97e72a0a9c0631d8c
h5py==3.10.0
hyo2.bag==1.2.0
kiwisolver==1.4.5
lxml==5.1.0
matplotlib==3.8.3
numpy==1.26.4
packaging==23.2
pillow==10.2.0
pyparsing==3.1.1
pyproj==3.6.1
python-dateutil==2.9.0.post0
setuptools==69.1.1
six==1.16.0
wheel==0.42.0
```

**Comment by giumas** [comment]
Thank you for the feedback.

I have pushed the [hyo2.abc2](https://github.com/hydroffice/hyo2_abc2) dependency on PyPI: https://pypi.org/project/hyo2.abc2/2.3.6/

Furthermore, hyo2.bag is now back on PyPI: https://pypi.org/project/hyo2.bag/#description

As build instruction, we now have GitHub actions for:

- Windows: https://github.com/hydroffice/hyo2_bag/actions/workflows/bag_on_windows.yml
- Linux: https://github.com/hydroffice/hyo2_bag/actions/workflows/bag_on_linux.yml

As such, I am closing this ticket.
